In [4]:
!pip install quandl

In [7]:
#Importing necessary pqckages
import quandl
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR
from sklearn.model_selection import train_test_split

In [8]:
#Get the stock data
df= quandl.get("NSE/TCS")

In [10]:
# Get the Close Price
df = df[['Close']]
#Take a look at the new data
print(df.head())

             Close
Date              
2004-08-25  987.95
2004-08-26  979.00
2004-08-27  962.65
2004-08-30  986.75
2004-08-31  988.10


In [11]:
# A variable for predicting 'n' days out into the future
forecast_out = 30 #'n=30' days
#Create another column (the target or dependent variable) shifted 'n' units up
df['Prediction'] = df[['Close']].shift(-forecast_out)
#print the new data set
print(df.tail())

              Close  Prediction
Date                           
2018-12-31  1893.05         NaN
2019-01-01  1902.80         NaN
2019-01-02  1923.30         NaN
2019-01-03  1899.95         NaN
2019-01-04  1876.85         NaN


In [12]:
X = np.array(df.drop(['Prediction'],1))

#Remove the last 'n' rows
X = X[:-forecast_out]
print(X)

[[ 987.95]
 [ 979.  ]
 [ 962.65]
 ...
 [1902.45]
 [1878.25]
 [1812.  ]]


In [13]:
### Create the dependent data set (y)  #####
# Convert the dataframe to a numpy array (All of the values including the NaN's)
y = np.array(df['Prediction'])
# Get all of the y values except the last 'n' rows
y = y[:-forecast_out]
print(y)

[1081.6  1097.1  1098.05 ... 1923.3  1899.95 1876.85]


In [14]:
# Split the data into 80% training and 20% testing
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [15]:
# Create and train the Support Vector Machine (Regressor)
svr_rbf = SVR(kernel='rbf', C=1e3, gamma=0.1)
svr_rbf.fit(x_train, y_train)

SVR(C=1000.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma=0.1,
  kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [16]:
# Testing Model: Score returns the coefficient of determination R^2 of the prediction. 
# The best possible score is 1.0
svm_confidence = svr_rbf.score(x_test, y_test)
print("svm confidence: ", svm_confidence)

svm confidence:  0.8829621111489354


In [17]:
# Create and train the Linear Regression  Model
lr = LinearRegression()
# Train the model
lr.fit(x_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [18]:
# Testing Model: Score returns the coefficient of determination R^2 of the prediction. 
# The best possible score is 1.0
lr_confidence = lr.score(x_test, y_test)
print("lr confidence: ", lr_confidence)

lr confidence:  0.9196842054564535


In [20]:
# Set x_forecast equal to the last 30 rows of the original data set from Close column
x_forecast = np.array(df.drop(['Prediction'],1))[-forecast_out:]
print(x_forecast)

[[1812.55]
 [1846.1 ]
 [1890.25]
 [1983.9 ]
 [1960.55]
 [1968.25]
 [1982.4 ]
 [2010.85]
 [2006.75]
 [1992.7 ]
 [1995.2 ]
 [1975.8 ]
 [2000.  ]
 [2016.8 ]
 [1982.6 ]
 [1989.75]
 [1994.3 ]
 [1987.85]
 [1968.45]
 [1954.05]
 [1895.8 ]
 [1918.5 ]
 [1889.2 ]
 [1908.95]
 [1896.05]
 [1893.05]
 [1902.8 ]
 [1923.3 ]
 [1899.95]
 [1876.85]]


In [21]:
# Print linear regression model predictions for the next 'n' days
lr_prediction = lr.predict(x_forecast)
print(lr_prediction)

# Print support vector regressor model predictions for the next 'n' days
svm_prediction = svr_rbf.predict(x_forecast)
print(svm_prediction)

[1809.94474915 1841.78716877 1883.69008461 1972.57361955 1950.41205478
 1957.72015108 1971.14996442 1998.15195662 1994.26063261 1980.92572961
 1983.29848815 1964.88588188 1987.85418455 2003.79912195 1971.33978511
 1978.12587453 1982.44429508 1976.32257804 1957.90997177 1944.24288257
 1888.95760857 1910.50225612 1882.69352602 1901.43831849 1889.19488442
 1886.34757417 1895.60133248 1915.05795252 1892.89638774 1870.97209883]
[1850.22727169 1956.05025695 1773.19491867 2256.06872536 1964.05981289
 2022.02277207 2160.76695457 1943.09434852 2089.14113104 2191.94775133
 1995.2192054  2048.79747787 2116.32931489 2265.94635827 2175.97680668
 2063.27976481 2098.1579481  2144.22545032 2012.69144034 2077.44610296
 2058.40894082 1970.57644862 1833.20286136 2013.93792459 2071.21605819
 1840.08414658 1974.69475154 1712.70337282 1630.18406022 1851.13333269]
